org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.15-SNAPSHOT
kotlin_version=2.3.0
fabric_version=0.155.2+26.1.2
fabric_language_kotlin_version=1.13.8+kotlin.2.3.0
hypixel_mod_api_version=1.0.2+build.1+mc26.1
jna_version=5.17.0

mod_version=1.0.0
maven_group=com.dinob.throwerlist
archives_base_name=throwerlist